### PR TITLE
[LOCAL-44] Strings: reverse sweep (auto)

### PR DESCRIPTION
**Pull request by string-sweep**
/cc @zendesk/i18n @zendesk/i18n-dev

### Risks
Low. English edits and title improvements.

### CODE REVIEW

**Comment by mariasica** [comment]
@hiroiguchi can you confirm? I edited for the project, if the change is incorrect, we can avoid merging and redo next week, but it did look like a typo?

**Comment by hiroiguchi** [comment]
@mariasica  @injuhwang has kindly confirmed with a developer, yes we can have the value `not fulfilled`.

**Comment by dadah89** [comment]
@zendesk/i18n could you make sure this is +1/merged? Keep having to revert the change in the rosetta string sweep pr's. Thanks!

**Comment by injuhwang** [comment]
👍 based on the dev's confirmation

**Comment by dadah89** [comment]
thanks!

**Pull request merged**
