### PR TITLE
[MI-736] Update app to just display a link to set up v2 of the integration

### PR DESCRIPTION
**Pull request by miogalang**
/cc @zendesk/mintegrations 
### Description

DO NOT MERGE UNTIL V2 IS RELEASED

Update the app to just display a link to set up version 2 of the integration

mio_s_amazing_zendesk_-_agent
### References
- JIRA: https://zendesk.atlassian.net/browse/MI-736
### Risks
- HIGH. App might not work and just display a link

### CODE REVIEW

**Comment by joseconsador** [comment]
👍

**Comment by jmramos02** [comment]
👍

**Comment by miogalang** [comment]
💇 @joseconsador

**Comment by miogalang** [comment]
:haircut_man: @joseconsador

**Pull request merged**
